name: richeable
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  jiffy: ^5.0.0
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0

  flutter_gen: ^5.0.1
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.5
  auto_route: ^5.0.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.7.0
  copy_with_extension: ^4.0.4

  connectivity_plus: ^2.3.9
  validators: ^3.0.0
  logger: ^1.1.0
  flutter_svg: ^1.1.5

  font_awesome_flutter: ^10.3.0
  responsive_framework: ^0.2.0
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.5

  google_mobile_ads: ^2.3.0

  tutorial_coach_mark: ^1.2.4
  drag_and_drop_lists: ^0.3.3
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  dotted_border: ^2.0.0+2
  smooth_page_indicator: ^1.0.0+2
  bot_toast: ^4.0.3
  flutter_picker: ^2.0.5
  dropdown_button2: ^1.8.5
  drop_down_list: ^0.0.4
  badges: ^2.0.3
  uuid: ^3.0.7
  flutter_rating_bar: ^4.0.1
  interactive_chart: ^0.3.4
  flutter_speed_dial: ^6.0.0
  faker: ^2.0.0

  just_audio: ^0.9.29
  currency_formatter: ^2.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.0
  freezed: ^2.0.3+1
  json_serializable: ^6.4.1
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2
  isar_generator: ^3.0.2
  copy_with_extension_gen: ^4.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/audio/
